project:
  type: website
  output-dir: docs
  render:
    - "blog/**/*.qmd"
    - "index.qmd"
    - "blog/index.qmd"
    - "404.qmd"
  post-render:
    - "cp -r static/. _site/"
  resources:
    - "_redirects.txt"

website:
  title: "The Great Equalizer"
  navbar:
    title: "the great equalizer"
    right:
      - href: blog/index.qmd
        text: BLOG
  favicon: icon-32.png
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
        
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    link-external-newwindow: true
    metadata:
      pagetitle: "The Great Equalizer"

editor: source

execute:
  freeze: auto
